name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Addition
      id: addition
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Addition
        setup-command: ''
        command: mvn -q -Dtest=CalculatorBotTest#grade_add test
        timeout: 10
        max-score: 25
    - name: Subtraction
      id: subtraction
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Subtraction
        setup-command: ''
        command: mvn -q -Dtest=CalculatorBotTest#grade_sub test
        timeout: 10
        max-score: 25
    - name: Multiplication
      id: multiplication
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Multiplication
        setup-command: ''
        command: mvn -q -Dtest=CalculatorBotTest#grade_mul test
        timeout: 10
        max-score: 25
    - name: Division
      id: division
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Division
        setup-command: ''
        command: mvn -q -Dtest=CalculatorBotTest#grade_div test
        timeout: 10
        max-score: 25
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ADDITION_RESULTS: "${{steps.addition.outputs.result}}"
        SUBTRACTION_RESULTS: "${{steps.subtraction.outputs.result}}"
        MULTIPLICATION_RESULTS: "${{steps.multiplication.outputs.result}}"
        DIVISION_RESULTS: "${{steps.division.outputs.result}}"
      with:
        runners: addition,subtraction,multiplication,division
